### ISSUE TITLE
Coverage with c8 and tsx reporting as 100% since version 4.3.0

### ISSUE THREAD

**Issue by OscarBarrett** [privatenumber/tsx#433]
### Acknowledgements

- [X] I searched existing issues before opening this one to avoid duplicates
- [X] I understand this is not a place for seek help, but to report a bug
- [X] I understand that the bug must be proven first with a minimal reproduction
- [X] I will be polite, respectful, and considerate of people's time and effort

### Minimal reproduction URL

https://github.com/OscarBarrett/tsx-coverage-issue

### Version

v4.6.2

### Node.js version

v20.10.0

### Package manager

yarn

### Operating system

Linux

### Problem & Expected behavior

We use c8 and tsx together when running our test suites, and since tsx version 4.3.0 any file that is imported in our tests gets 100% coverage.
Locking to tsx 4.2.1, we get the expected coverage.

Assuming this is related to #405

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by andreashuber69** [comment]
I have the same issue. FWIW, you can work around this by running tests on the built js output. If you have TypeScript generate .map files, then the CC output should look the same as before (i.e. reported on ts files rather than js files). Here's an example of the changes necessary (besides building with tsc):

https://github.com/andreashuber69/verify-coldcard-dice-seed/commit/35b72b9bcc4a087790848db0afb3df9407b0d919

**Comment by jbergstroem** [comment]
Ran into the same; just wanted to chip in and confirm that downgrading works.

**Comment by privatenumber** [comment]
I haven't investigated this but I'm thinking this is as simple as removing this check so sourcemaps are always inlined:
https://github.com/privatenumber/tsx/blob/8c778919496a8164ec63d0b488c805bce1aba839/src/source-map.ts#L23

There will need to be tests though. PR welcome if anyone wants to tackle.

**Comment by kallekj** [comment]
Test coverage works in 4.7.0 if I run mocha with source-map-support/register. 
My `.mocharc` file to run it with tsx/esm:
```json
{
  "import": "tsx/esm",
  "require": "source-map-support/register"
}

```

**Comment by cenfun** [comment]
This issue is related to the source maps conversion with [`v8-to-istanbul`](https://github.com/istanbuljs/v8-to-istanbul), and it is not related to tsx. see [here](https://github.com/jestjs/jest/issues/11188)
V8 provides the correct coverage data
```js
[
  [ { startOffset: 0, endOffset: 592, count: 1 } ],
  [ { startOffset: 47, endOffset: 113, count: 2 } ],
  [ { startOffset: 114, endOffset: 143, count: 1 } ],
  [ { startOffset: 161, endOffset: 195, count: 0 } ]  <- uncovered 
]
```
However, it has not been applied to the source file `index.ts`
```
[
  CovLine { line: 1, startCol: 0, endCol: 0, count: 1, ignore: false }
]
```
I built a tool that can be used to generate native v8 coverage reports, you might have a try
```sh
npm i monocart-coverage-reports -g
mcr npx tsx bin/test.ts -r v8,console-details --entryFilter **/*.ts

┌─────────────────┬──────────┬────────────┬──────────┬───────────┬──────────┬─────────────────┐
│ Name            │    Bytes │ Statements │ Branches │ Functions │    Lines │ Uncovered Lines │
├─────────────────┼──────────┼────────────┼──────────┼───────────┼──────────┼─────────────────┤
│ bin             │          │            │          │           │          │                 │
│ └ test.ts       │ 100.00 % │   100.00 % │          │           │ 100.00 % │                 │
│ tests           │          │            │          │           │          │                 │
│ └ maths.spec.ts │ 100.00 % │   100.00 % │ 100.00 % │  100.00 % │ 100.00 % │                 │
│ index.ts        │  55.47 % │    50.00 % │ 100.00 % │   50.00 % │  50.00 % │ 5-7             │
├─────────────────┼──────────┼────────────┼──────────┼───────────┼──────────┼─────────────────┤
│ Summary         │  89.90 % │    75.00 % │ 100.00 % │   66.67 % │  84.21 % │                 │
└─────────────────┴──────────┴────────────┴──────────┴───────────┴──────────┴─────────────────┘
```

**Comment by privatenumber** [comment]
Seems like both versions of tsx in the reproduction doesn't work in the latest version of Node, but the reproduction still works fine with Node v20.10.0.

I'm curious what happened between tsx v4.2.1 and v4.6.2 that broke c8 in Node v20.10.0.

**Comment by cenfun** [comment]
@privatenumber the generated sourcemap content could be different
- <= tsx 4.2.1 generating sourcemap with `source-map-support`
- >= tsx 4.3.0 generating sourcemap with native Node.js (removed `source-map-support`)

**Comment by privatenumber** [comment]
This has been completed in the development repo.

**Comment by privatenumber** [comment]
:tada: This issue has been resolved in v4.10.4

If you appreciate this project, please consider [supporting this project by sponsoring](https://github.com/sponsors/privatenumber) :heart: :pray:

**Comment by rozzilla** [comment]
Hi @privatenumber 👋🏼 😊 
I still have the issue. Basically, if I run Node tests with `tsx` and `c8` as a coverage tool on the latest versions of both, I get the coverage at 100% for all tests. While if I downgrade `tsx` to an older version (f.e. `4.2.0`), I get the right coverage. Do you know if this can be solved by passing a specific setting?

**Comment by wellwelwel** [comment]
An observation that I find interesting to relate is that after `v4.10.4`, the coverage of a project dropped by almost **2%**.
Looking at the differences between **tsx** versions, I noticed that it was mainly the imports of types. 

To fix it, I just used **c8**'s recommendation:

```ts
/* c8 ignore next */
import type { SomeType } from '../some-type.js';
```

> I don't see this as an issue, so I preferred to add it to the context of this issue.

@privatenumber, thanks for this project and the fix 💙
